# __init__.py

from flymazerl.agents import base
from flymazerl.agents import classical
from flymazerl.agents import nn
from flymazerl.agents import phenomenological
from flymazerl.agents import qlearning

from flymazerl.agents.base import (FlYMazeAgent, RandomAgent,)
from flymazerl.agents.classical import (CQLearner, CQLearner_acceptreject,
                                        CQLearner_egreedy, CQLearner_esoftmax,
                                        CQLearner_softmax, DECQLearner,
                                        DECQLearner_acceptreject,
                                        DECQLearner_egreedy,
                                        DECQLearner_esoftmax,
                                        DECQLearner_softmax, DEQLearner,
                                        DEQLearner_acceptreject,
                                        DEQLearner_egreedy,
                                        DEQLearner_esoftmax,
                                        DEQLearner_softmax, DFCQLearner,
                                        DFCQLearner_acceptreject,
                                        DFCQLearner_egreedy,
                                        DFCQLearner_esoftmax,
                                        DFCQLearner_softmax, DFOSCQLearner,
                                        DFOSCQLearner_acceptreject,
                                        DFOSCQLearner_egreedy,
                                        DFOSCQLearner_esoftmax,
                                        DFOSCQLearner_softmax, DFOSQLearner,
                                        DFOSQLearner_acceptreject,
                                        DFOSQLearner_egreedy,
                                        DFOSQLearner_esoftmax,
                                        DFOSQLearner_softmax, DFQLearner,
                                        DFQLearner_acceptreject,
                                        DFQLearner_egreedy,
                                        DFQLearner_esoftmax,
                                        DFQLearner_softmax, DQLearner,
                                        DQLearner_egreedy, DQLearner_esoftmax,
                                        DQLearner_softmax, ESARSALearner,
                                        ESARSALearner_acceptreject,
                                        ESARSALearner_egreedy,
                                        ESARSALearner_esoftmax,
                                        ESARSALearner_softmax, FCQLearner,
                                        FCQLearner_acceptreject,
                                        FCQLearner_egreedy,
                                        FCQLearner_esoftmax,
                                        FCQLearner_softmax, FHCQLearner,
                                        FHCQLearner_acceptreject,
                                        FHCQLearner_egreedy,
                                        FHCQLearner_esoftmax,
                                        FHCQLearner_softmax, FHQLearner,
                                        FHQLearner_acceptreject,
                                        FHQLearner_egreedy,
                                        FHQLearner_esoftmax,
                                        FHQLearner_softmax, FOSCQLearner,
                                        FOSCQLearner_acceptreject,
                                        FOSCQLearner_egreedy,
                                        FOSCQLearner_esoftmax,
                                        FOSCQLearner_softmax, FOSQLearner,
                                        FOSQLearner_acceptreject,
                                        FOSQLearner_egreedy,
                                        FOSQLearner_esoftmax,
                                        FOSQLearner_softmax, FQLearner,
                                        FQLearner_acceptreject,
                                        FQLearner_egreedy, FQLearner_esoftmax,
                                        FQLearner_softmax,
                                        ForgettingRewardLearner,
                                        ForgettingRewardLearner_acceptreject,
                                        ForgettingRewardLearner_egreedy,
                                        ForgettingRewardLearner_esoftmax,
                                        ForgettingRewardLearner_softmax,
                                        HCQLearner, HCQLearner_acceptreject,
                                        HCQLearner_egreedy,
                                        HCQLearner_esoftmax,
                                        HCQLearner_softmax, HQLearner,
                                        HQLearner_acceptreject,
                                        HQLearner_egreedy, HQLearner_esoftmax,
                                        HQLearner_softmax, IQLearner,
                                        IQLearner_acceptreject,
                                        IQLearner_egreedy, IQLearner_esoftmax,
                                        IQLearner_softmax, OSCQLearner,
                                        OSCQLearner_acceptreject,
                                        OSCQLearner_egreedy,
                                        OSCQLearner_esoftmax,
                                        OSCQLearner_softmax, OSQLearner,
                                        OSQLearner_acceptreject,
                                        OSQLearner_egreedy,
                                        OSQLearner_esoftmax,
                                        OSQLearner_softmax, RewardLearner,
                                        RewardLearner_acceptreject,
                                        RewardLearner_egreedy,
                                        RewardLearner_esoftmax,
                                        RewardLearner_softmax, SARSALearner,
                                        SARSALearner_acceptreject,
                                        SARSALearner_egreedy,
                                        SARSALearner_esoftmax,
                                        SARSALearner_softmax,)
from flymazerl.agents.nn import (GFFNN, GQLearner, GRNNLearner, GRUNN, LSTMNN,
                                 VanillaRNN, ffnn, rnn,)
from flymazerl.agents.phenomenological import (BayesianIdealObserver,
                                               CATIELearner,)
from flymazerl.agents.qlearning import (DEIQLearner, DEIQLearnerHM,
                                        DEIQLearnerHM_acceptreject,
                                        DEIQLearner_acceptreject,
                                        DEIQLearner_egreedy,
                                        DEIQLearner_esoftmax,
                                        DEIQLearner_softmax, DELTQLearner,
                                        DELTQLearnerHM,
                                        DELTQLearnerHM_acceptreject,
                                        DELTQLearner_acceptreject,
                                        DELTQLearner_egreedy,
                                        DELTQLearner_esoftmax,
                                        DELTQLearner_softmax, DFIQLearner,
                                        DFIQLearnerHM,
                                        DFIQLearnerHM_acceptreject,
                                        DFIQLearner_acceptreject,
                                        DFIQLearner_egreedy,
                                        DFIQLearner_esoftmax,
                                        DFIQLearner_softmax, DFLTQLearner,
                                        DFLTQLearnerHM,
                                        DFLTQLearnerHM_acceptreject,
                                        DFLTQLearner_acceptreject,
                                        DFLTQLearner_egreedy,
                                        DFLTQLearner_esoftmax,
                                        DFLTQLearner_softmax, DFOSCQLearner,
                                        DFOSCQLearner_acceptreject,
                                        DFOSCQLearner_egreedy,
                                        DFOSCQLearner_esoftmax,
                                        DFOSCQLearner_softmax, DFOSQLearner,
                                        DFOSQLearner_acceptreject,
                                        DFOSQLearner_egreedy,
                                        DFOSQLearner_esoftmax,
                                        DFOSQLearner_softmax, ESARSALearner,
                                        ESARSALearnerHM,
                                        ESARSALearnerHM_acceptreject,
                                        ESARSALearner_acceptreject,
                                        ESARSALearner_egreedy,
                                        ESARSALearner_esoftmax,
                                        ESARSALearner_softmax, FHCQLearner,
                                        FHCQLearner_acceptreject,
                                        FHCQLearner_egreedy,
                                        FHCQLearner_esoftmax,
                                        FHCQLearner_softmax, FHQLearner,
                                        FHQLearner_acceptreject,
                                        FHQLearner_egreedy,
                                        FHQLearner_esoftmax,
                                        FHQLearner_softmax, FIQLearner,
                                        FIQLearnerHM,
                                        FIQLearnerHM_acceptreject,
                                        FIQLearner_acceptreject,
                                        FIQLearner_egreedy,
                                        FIQLearner_esoftmax,
                                        FIQLearner_softmax, FLTQLearner,
                                        FLTQLearnerHM,
                                        FLTQLearnerHM_acceptreject,
                                        FLTQLearner_acceptreject,
                                        FLTQLearner_egreedy,
                                        FLTQLearner_esoftmax,
                                        FLTQLearner_softmax, FOSCQLearner,
                                        FOSCQLearner_acceptreject,
                                        FOSCQLearner_egreedy,
                                        FOSCQLearner_esoftmax,
                                        FOSCQLearner_softmax, FOSQLearner,
                                        FOSQLearner_acceptreject,
                                        FOSQLearner_egreedy,
                                        FOSQLearner_esoftmax,
                                        FOSQLearner_softmax, FRPEFreeLearner,
                                        FRPEFreeLearnerHM,
                                        FRPEFreeLearnerHM_acceptreject,
                                        FRPEFreeLearner_acceptreject,
                                        FRPEFreeLearner_egreedy,
                                        FRPEFreeLearner_esoftmax,
                                        FRPEFreeLearner_softmax, HCQLearner,
                                        HCQLearner_acceptreject,
                                        HCQLearner_egreedy,
                                        HCQLearner_esoftmax,
                                        HCQLearner_softmax, HQLearner,
                                        HQLearner_acceptreject,
                                        HQLearner_egreedy, HQLearner_esoftmax,
                                        HQLearner_softmax, IQLearner,
                                        IQLearnerHM, IQLearnerHM_acceptreject,
                                        IQLearner_acceptreject,
                                        IQLearner_egreedy, IQLearner_esoftmax,
                                        IQLearner_softmax, LTQLearner,
                                        LTQLearnerHM,
                                        LTQLearnerHM_acceptreject,
                                        LTQLearner_acceptreject,
                                        LTQLearner_egreedy,
                                        LTQLearner_esoftmax,
                                        LTQLearner_softmax, OSCQLearner,
                                        OSCQLearner_acceptreject,
                                        OSCQLearner_egreedy,
                                        OSCQLearner_esoftmax,
                                        OSCQLearner_softmax, OSQLearner,
                                        OSQLearner_acceptreject,
                                        OSQLearner_egreedy,
                                        OSQLearner_esoftmax,
                                        OSQLearner_softmax, RPEFreeLearner,
                                        RPEFreeLearnerHM,
                                        RPEFreeLearnerHM_acceptreject,
                                        RPEFreeLearner_acceptreject,
                                        RPEFreeLearner_egreedy,
                                        RPEFreeLearner_esoftmax,
                                        RPEFreeLearner_softmax, SARSALearner,
                                        SARSALearnerHM,
                                        SARSALearnerHM_acceptreject,
                                        SARSALearner_acceptreject,
                                        SARSALearner_egreedy,
                                        SARSALearner_esoftmax,
                                        SARSALearner_softmax, de_i, de_lt,
                                        df_i, df_i_os, df_lt, df_lt_os, esa,
                                        f_i, f_i_hv, f_i_os, f_lt, f_lt_hv,
                                        f_lt_os, f_rf, i, i_hv, i_os, lt,
                                        lt_hv, lt_os, rf, sa,)

__all__ = ['BayesianIdealObserver', 'CATIELearner', 'CQLearner',
           'CQLearner_acceptreject', 'CQLearner_egreedy', 'CQLearner_esoftmax',
           'CQLearner_softmax', 'DECQLearner', 'DECQLearner_acceptreject',
           'DECQLearner_egreedy', 'DECQLearner_esoftmax',
           'DECQLearner_softmax', 'DEIQLearner', 'DEIQLearnerHM',
           'DEIQLearnerHM_acceptreject', 'DEIQLearner_acceptreject',
           'DEIQLearner_egreedy', 'DEIQLearner_esoftmax',
           'DEIQLearner_softmax', 'DELTQLearner', 'DELTQLearnerHM',
           'DELTQLearnerHM_acceptreject', 'DELTQLearner_acceptreject',
           'DELTQLearner_egreedy', 'DELTQLearner_esoftmax',
           'DELTQLearner_softmax', 'DEQLearner', 'DEQLearner_acceptreject',
           'DEQLearner_egreedy', 'DEQLearner_esoftmax', 'DEQLearner_softmax',
           'DFCQLearner', 'DFCQLearner_acceptreject', 'DFCQLearner_egreedy',
           'DFCQLearner_esoftmax', 'DFCQLearner_softmax', 'DFIQLearner',
           'DFIQLearnerHM', 'DFIQLearnerHM_acceptreject',
           'DFIQLearner_acceptreject', 'DFIQLearner_egreedy',
           'DFIQLearner_esoftmax', 'DFIQLearner_softmax', 'DFLTQLearner',
           'DFLTQLearnerHM', 'DFLTQLearnerHM_acceptreject',
           'DFLTQLearner_acceptreject', 'DFLTQLearner_egreedy',
           'DFLTQLearner_esoftmax', 'DFLTQLearner_softmax', 'DFOSCQLearner',
           'DFOSCQLearner_acceptreject', 'DFOSCQLearner_egreedy',
           'DFOSCQLearner_esoftmax', 'DFOSCQLearner_softmax', 'DFOSQLearner',
           'DFOSQLearner_acceptreject', 'DFOSQLearner_egreedy',
           'DFOSQLearner_esoftmax', 'DFOSQLearner_softmax', 'DFQLearner',
           'DFQLearner_acceptreject', 'DFQLearner_egreedy',
           'DFQLearner_esoftmax', 'DFQLearner_softmax', 'DQLearner',
           'DQLearner_egreedy', 'DQLearner_esoftmax', 'DQLearner_softmax',
           'ESARSALearner', 'ESARSALearnerHM', 'ESARSALearnerHM_acceptreject',
           'ESARSALearner_acceptreject', 'ESARSALearner_egreedy',
           'ESARSALearner_esoftmax', 'ESARSALearner_softmax', 'FCQLearner',
           'FCQLearner_acceptreject', 'FCQLearner_egreedy',
           'FCQLearner_esoftmax', 'FCQLearner_softmax', 'FHCQLearner',
           'FHCQLearner_acceptreject', 'FHCQLearner_egreedy',
           'FHCQLearner_esoftmax', 'FHCQLearner_softmax', 'FHQLearner',
           'FHQLearner_acceptreject', 'FHQLearner_egreedy',
           'FHQLearner_esoftmax', 'FHQLearner_softmax', 'FIQLearner',
           'FIQLearnerHM', 'FIQLearnerHM_acceptreject',
           'FIQLearner_acceptreject', 'FIQLearner_egreedy',
           'FIQLearner_esoftmax', 'FIQLearner_softmax', 'FLTQLearner',
           'FLTQLearnerHM', 'FLTQLearnerHM_acceptreject',
           'FLTQLearner_acceptreject', 'FLTQLearner_egreedy',
           'FLTQLearner_esoftmax', 'FLTQLearner_softmax', 'FOSCQLearner',
           'FOSCQLearner_acceptreject', 'FOSCQLearner_egreedy',
           'FOSCQLearner_esoftmax', 'FOSCQLearner_softmax', 'FOSQLearner',
           'FOSQLearner_acceptreject', 'FOSQLearner_egreedy',
           'FOSQLearner_esoftmax', 'FOSQLearner_softmax', 'FQLearner',
           'FQLearner_acceptreject', 'FQLearner_egreedy', 'FQLearner_esoftmax',
           'FQLearner_softmax', 'FRPEFreeLearner', 'FRPEFreeLearnerHM',
           'FRPEFreeLearnerHM_acceptreject', 'FRPEFreeLearner_acceptreject',
           'FRPEFreeLearner_egreedy', 'FRPEFreeLearner_esoftmax',
           'FRPEFreeLearner_softmax', 'FlYMazeAgent',
           'ForgettingRewardLearner', 'ForgettingRewardLearner_acceptreject',
           'ForgettingRewardLearner_egreedy',
           'ForgettingRewardLearner_esoftmax',
           'ForgettingRewardLearner_softmax', 'GFFNN', 'GQLearner',
           'GRNNLearner', 'GRUNN', 'HCQLearner', 'HCQLearner_acceptreject',
           'HCQLearner_egreedy', 'HCQLearner_esoftmax', 'HCQLearner_softmax',
           'HQLearner', 'HQLearner_acceptreject', 'HQLearner_egreedy',
           'HQLearner_esoftmax', 'HQLearner_softmax', 'IQLearner',
           'IQLearnerHM', 'IQLearnerHM_acceptreject', 'IQLearner_acceptreject',
           'IQLearner_egreedy', 'IQLearner_esoftmax', 'IQLearner_softmax',
           'LSTMNN', 'LTQLearner', 'LTQLearnerHM', 'LTQLearnerHM_acceptreject',
           'LTQLearner_acceptreject', 'LTQLearner_egreedy',
           'LTQLearner_esoftmax', 'LTQLearner_softmax', 'OSCQLearner',
           'OSCQLearner_acceptreject', 'OSCQLearner_egreedy',
           'OSCQLearner_esoftmax', 'OSCQLearner_softmax', 'OSQLearner',
           'OSQLearner_acceptreject', 'OSQLearner_egreedy',
           'OSQLearner_esoftmax', 'OSQLearner_softmax', 'RPEFreeLearner',
           'RPEFreeLearnerHM', 'RPEFreeLearnerHM_acceptreject',
           'RPEFreeLearner_acceptreject', 'RPEFreeLearner_egreedy',
           'RPEFreeLearner_esoftmax', 'RPEFreeLearner_softmax', 'RandomAgent',
           'RewardLearner', 'RewardLearner_acceptreject',
           'RewardLearner_egreedy', 'RewardLearner_esoftmax',
           'RewardLearner_softmax', 'SARSALearner', 'SARSALearnerHM',
           'SARSALearnerHM_acceptreject', 'SARSALearner_acceptreject',
           'SARSALearner_egreedy', 'SARSALearner_esoftmax',
           'SARSALearner_softmax', 'VanillaRNN', 'base', 'classical', 'de_i',
           'de_lt', 'df_i', 'df_i_os', 'df_lt', 'df_lt_os', 'esa', 'f_i',
           'f_i_hv', 'f_i_os', 'f_lt', 'f_lt_hv', 'f_lt_os', 'f_rf', 'ffnn',
           'i', 'i_hv', 'i_os', 'lt', 'lt_hv', 'lt_os', 'nn',
           'phenomenological', 'qlearning', 'rf', 'rnn', 'sa']
