# __init__.py

from flymazerl import agents
from flymazerl import gym
from flymazerl import optimize
from flymazerl import utils

from flymazerl.agents import (BayesianIdealObserver, CATIELearner, CQLearner,
                              CQLearner_acceptreject, CQLearner_egreedy,
                              CQLearner_esoftmax, CQLearner_softmax,
                              DECQLearner, DECQLearner_acceptreject,
                              DECQLearner_egreedy, DECQLearner_esoftmax,
                              DECQLearner_softmax, DEIQLearner, DEIQLearnerHM,
                              DEIQLearnerHM_acceptreject,
                              DEIQLearner_acceptreject, DEIQLearner_egreedy,
                              DEIQLearner_esoftmax, DEIQLearner_softmax,
                              DELTQLearner, DELTQLearnerHM,
                              DELTQLearnerHM_acceptreject,
                              DELTQLearner_acceptreject, DELTQLearner_egreedy,
                              DELTQLearner_esoftmax, DELTQLearner_softmax,
                              DEQLearner, DEQLearner_acceptreject,
                              DEQLearner_egreedy, DEQLearner_esoftmax,
                              DEQLearner_softmax, DFCQLearner,
                              DFCQLearner_acceptreject, DFCQLearner_egreedy,
                              DFCQLearner_esoftmax, DFCQLearner_softmax,
                              DFHCQLearner, DFHCQLearner_acceptreject,
                              DFHCQLearner_egreedy, DFHCQLearner_esoftmax,
                              DFHCQLearner_softmax, DFHQLearner,
                              DFHQLearner_acceptreject, DFHQLearner_egreedy,
                              DFHQLearner_esoftmax, DFHQLearner_softmax,
                              DFIQLearner, DFIQLearnerHM,
                              DFIQLearnerHM_acceptreject,
                              DFIQLearner_acceptreject, DFIQLearner_egreedy,
                              DFIQLearner_esoftmax, DFIQLearner_softmax,
                              DFLTQLearner, DFLTQLearnerHM,
                              DFLTQLearnerHM_acceptreject,
                              DFLTQLearner_acceptreject, DFLTQLearner_egreedy,
                              DFLTQLearner_esoftmax, DFLTQLearner_softmax,
                              DFOSCQLearner, DFOSCQLearner_acceptreject,
                              DFOSCQLearner_egreedy, DFOSCQLearner_esoftmax,
                              DFOSCQLearner_softmax, DFOSQLearner,
                              DFOSQLearner_acceptreject, DFOSQLearner_egreedy,
                              DFOSQLearner_esoftmax, DFOSQLearner_softmax,
                              DFQLearner, DFQLearner_acceptreject,
                              DFQLearner_egreedy, DFQLearner_esoftmax,
                              DFQLearner_softmax, DQLearner, DQLearner_egreedy,
                              DQLearner_esoftmax, DQLearner_softmax,
                              ESARSALearner, ESARSALearnerHM,
                              ESARSALearnerHM_acceptreject,
                              ESARSALearner_acceptreject,
                              ESARSALearner_egreedy, ESARSALearner_esoftmax,
                              ESARSALearner_softmax, FCQLearner,
                              FCQLearner_acceptreject, FCQLearner_egreedy,
                              FCQLearner_esoftmax, FCQLearner_softmax,
                              FHCQLearner, FHCQLearner_acceptreject,
                              FHCQLearner_egreedy, FHCQLearner_esoftmax,
                              FHCQLearner_softmax, FHQLearner,
                              FHQLearner_acceptreject, FHQLearner_egreedy,
                              FHQLearner_esoftmax, FHQLearner_softmax,
                              FIQLearner, FIQLearnerHM,
                              FIQLearnerHM_acceptreject,
                              FIQLearner_acceptreject, FIQLearner_egreedy,
                              FIQLearner_esoftmax, FIQLearner_softmax,
                              FLTQLearner, FLTQLearnerHM,
                              FLTQLearnerHM_acceptreject,
                              FLTQLearner_acceptreject, FLTQLearner_egreedy,
                              FLTQLearner_esoftmax, FLTQLearner_softmax,
                              FOSCQLearner, FOSCQLearner_acceptreject,
                              FOSCQLearner_egreedy, FOSCQLearner_esoftmax,
                              FOSCQLearner_softmax, FOSQLearner,
                              FOSQLearner_acceptreject, FOSQLearner_egreedy,
                              FOSQLearner_esoftmax, FOSQLearner_softmax,
                              FQLearner, FQLearner_acceptreject,
                              FQLearner_egreedy, FQLearner_esoftmax,
                              FQLearner_softmax, FRPEFreeLearner,
                              FRPEFreeLearnerHM,
                              FRPEFreeLearnerHM_acceptreject,
                              FRPEFreeLearner_acceptreject,
                              FRPEFreeLearner_egreedy,
                              FRPEFreeLearner_esoftmax,
                              FRPEFreeLearner_softmax, FlYMazeAgent,
                              ForgettingRewardLearner,
                              ForgettingRewardLearner_acceptreject,
                              ForgettingRewardLearner_egreedy,
                              ForgettingRewardLearner_esoftmax,
                              ForgettingRewardLearner_softmax, GFFNN,
                              GQLearner, GRNNLearner, GRUNN, HCQLearner,
                              HCQLearner_acceptreject, HCQLearner_egreedy,
                              HCQLearner_esoftmax, HCQLearner_softmax,
                              HQLearner, HQLearner_acceptreject,
                              HQLearner_egreedy, HQLearner_esoftmax,
                              HQLearner_softmax, IQLearner, IQLearnerHM,
                              IQLearnerHM_acceptreject, IQLearner_acceptreject,
                              IQLearner_egreedy, IQLearner_esoftmax,
                              IQLearner_softmax, LSTMNN, LTQLearner,
                              LTQLearnerHM, LTQLearnerHM_acceptreject,
                              LTQLearner_acceptreject, LTQLearner_egreedy,
                              LTQLearner_esoftmax, LTQLearner_softmax,
                              OSCQLearner, OSCQLearner_acceptreject,
                              OSCQLearner_egreedy, OSCQLearner_esoftmax,
                              OSCQLearner_softmax, OSQLearner,
                              OSQLearner_acceptreject, OSQLearner_egreedy,
                              OSQLearner_esoftmax, OSQLearner_softmax,
                              RPEFreeLearner, RPEFreeLearnerHM,
                              RPEFreeLearnerHM_acceptreject,
                              RPEFreeLearner_acceptreject,
                              RPEFreeLearner_egreedy, RPEFreeLearner_esoftmax,
                              RPEFreeLearner_softmax, RandomAgent,
                              RewardLearner, RewardLearner_acceptreject,
                              RewardLearner_egreedy, RewardLearner_esoftmax,
                              RewardLearner_softmax, SARSALearner,
                              SARSALearnerHM, SARSALearnerHM_acceptreject,
                              SARSALearner_acceptreject, SARSALearner_egreedy,
                              SARSALearner_esoftmax, SARSALearner_softmax,
                              VanillaRNN, base, classical, de_i, de_lt, df_i,
                              df_i_os, df_lt, df_lt_os, esa, f_i, f_i_hv,
                              f_i_os, f_lt, f_lt_hv, f_lt_os, f_rf, ffnn, i,
                              i_hv, i_os, lt, lt_hv, lt_os, nn,
                              phenomenological, qlearning, rf, rnn, sa,)
from flymazerl.gym import (environment, ymaze_RNN, ymaze_baiting,
                           ymaze_dynamic, ymaze_fixedreward, ymaze_gammatest,
                           ymaze_static,)
from flymazerl.optimize import (generate_random_child, genetic_optimization,
                                phi, static, thermal_annealing,
                                thermal_reshuffle,)
from flymazerl.utils import (FLYMAZERL_PATH, draw_optimization_history,
                             draw_schedule, evaluation,
                             generate_params_from_fits,
                             generate_random_schedule,
                             generate_random_schedule_with_blocks, generators,
                             get_agent_bias, get_agent_failure,
                             get_agent_history, get_agent_performance,
                             get_agent_separation, get_agent_value_history,
                             get_continuous_cmap, get_schedule_fitness,
                             get_schedule_histories, get_schedule_values,
                             hex_to_rgb, rgb_to_dec, visualization,)

__all__ = ['BayesianIdealObserver', 'CATIELearner', 'CQLearner',
           'CQLearner_acceptreject', 'CQLearner_egreedy', 'CQLearner_esoftmax',
           'CQLearner_softmax', 'DECQLearner', 'DECQLearner_acceptreject',
           'DECQLearner_egreedy', 'DECQLearner_esoftmax',
           'DECQLearner_softmax', 'DEIQLearner', 'DEIQLearnerHM',
           'DEIQLearnerHM_acceptreject', 'DEIQLearner_acceptreject',
           'DEIQLearner_egreedy', 'DEIQLearner_esoftmax',
           'DEIQLearner_softmax', 'DELTQLearner', 'DELTQLearnerHM',
           'DELTQLearnerHM_acceptreject', 'DELTQLearner_acceptreject',
           'DELTQLearner_egreedy', 'DELTQLearner_esoftmax',
           'DELTQLearner_softmax', 'DEQLearner', 'DEQLearner_acceptreject',
           'DEQLearner_egreedy', 'DEQLearner_esoftmax', 'DEQLearner_softmax',
           'DFCQLearner', 'DFCQLearner_acceptreject', 'DFCQLearner_egreedy',
           'DFCQLearner_esoftmax', 'DFCQLearner_softmax', 'DFHCQLearner',
           'DFHCQLearner_acceptreject', 'DFHCQLearner_egreedy',
           'DFHCQLearner_esoftmax', 'DFHCQLearner_softmax', 'DFHQLearner',
           'DFHQLearner_acceptreject', 'DFHQLearner_egreedy',
           'DFHQLearner_esoftmax', 'DFHQLearner_softmax', 'DFIQLearner',
           'DFIQLearnerHM', 'DFIQLearnerHM_acceptreject',
           'DFIQLearner_acceptreject', 'DFIQLearner_egreedy',
           'DFIQLearner_esoftmax', 'DFIQLearner_softmax', 'DFLTQLearner',
           'DFLTQLearnerHM', 'DFLTQLearnerHM_acceptreject',
           'DFLTQLearner_acceptreject', 'DFLTQLearner_egreedy',
           'DFLTQLearner_esoftmax', 'DFLTQLearner_softmax', 'DFOSCQLearner',
           'DFOSCQLearner_acceptreject', 'DFOSCQLearner_egreedy',
           'DFOSCQLearner_esoftmax', 'DFOSCQLearner_softmax', 'DFOSQLearner',
           'DFOSQLearner_acceptreject', 'DFOSQLearner_egreedy',
           'DFOSQLearner_esoftmax', 'DFOSQLearner_softmax', 'DFQLearner',
           'DFQLearner_acceptreject', 'DFQLearner_egreedy',
           'DFQLearner_esoftmax', 'DFQLearner_softmax', 'DQLearner',
           'DQLearner_egreedy', 'DQLearner_esoftmax', 'DQLearner_softmax',
           'ESARSALearner', 'ESARSALearnerHM', 'ESARSALearnerHM_acceptreject',
           'ESARSALearner_acceptreject', 'ESARSALearner_egreedy',
           'ESARSALearner_esoftmax', 'ESARSALearner_softmax', 'FCQLearner',
           'FCQLearner_acceptreject', 'FCQLearner_egreedy',
           'FCQLearner_esoftmax', 'FCQLearner_softmax', 'FHCQLearner',
           'FHCQLearner_acceptreject', 'FHCQLearner_egreedy',
           'FHCQLearner_esoftmax', 'FHCQLearner_softmax', 'FHQLearner',
           'FHQLearner_acceptreject', 'FHQLearner_egreedy',
           'FHQLearner_esoftmax', 'FHQLearner_softmax', 'FIQLearner',
           'FIQLearnerHM', 'FIQLearnerHM_acceptreject',
           'FIQLearner_acceptreject', 'FIQLearner_egreedy',
           'FIQLearner_esoftmax', 'FIQLearner_softmax', 'FLTQLearner',
           'FLTQLearnerHM', 'FLTQLearnerHM_acceptreject',
           'FLTQLearner_acceptreject', 'FLTQLearner_egreedy',
           'FLTQLearner_esoftmax', 'FLTQLearner_softmax', 'FLYMAZERL_PATH',
           'FOSCQLearner', 'FOSCQLearner_acceptreject', 'FOSCQLearner_egreedy',
           'FOSCQLearner_esoftmax', 'FOSCQLearner_softmax', 'FOSQLearner',
           'FOSQLearner_acceptreject', 'FOSQLearner_egreedy',
           'FOSQLearner_esoftmax', 'FOSQLearner_softmax', 'FQLearner',
           'FQLearner_acceptreject', 'FQLearner_egreedy', 'FQLearner_esoftmax',
           'FQLearner_softmax', 'FRPEFreeLearner', 'FRPEFreeLearnerHM',
           'FRPEFreeLearnerHM_acceptreject', 'FRPEFreeLearner_acceptreject',
           'FRPEFreeLearner_egreedy', 'FRPEFreeLearner_esoftmax',
           'FRPEFreeLearner_softmax', 'FlYMazeAgent',
           'ForgettingRewardLearner', 'ForgettingRewardLearner_acceptreject',
           'ForgettingRewardLearner_egreedy',
           'ForgettingRewardLearner_esoftmax',
           'ForgettingRewardLearner_softmax', 'GFFNN', 'GQLearner',
           'GRNNLearner', 'GRUNN', 'HCQLearner', 'HCQLearner_acceptreject',
           'HCQLearner_egreedy', 'HCQLearner_esoftmax', 'HCQLearner_softmax',
           'HQLearner', 'HQLearner_acceptreject', 'HQLearner_egreedy',
           'HQLearner_esoftmax', 'HQLearner_softmax', 'IQLearner',
           'IQLearnerHM', 'IQLearnerHM_acceptreject', 'IQLearner_acceptreject',
           'IQLearner_egreedy', 'IQLearner_esoftmax', 'IQLearner_softmax',
           'LSTMNN', 'LTQLearner', 'LTQLearnerHM', 'LTQLearnerHM_acceptreject',
           'LTQLearner_acceptreject', 'LTQLearner_egreedy',
           'LTQLearner_esoftmax', 'LTQLearner_softmax', 'OSCQLearner',
           'OSCQLearner_acceptreject', 'OSCQLearner_egreedy',
           'OSCQLearner_esoftmax', 'OSCQLearner_softmax', 'OSQLearner',
           'OSQLearner_acceptreject', 'OSQLearner_egreedy',
           'OSQLearner_esoftmax', 'OSQLearner_softmax', 'RPEFreeLearner',
           'RPEFreeLearnerHM', 'RPEFreeLearnerHM_acceptreject',
           'RPEFreeLearner_acceptreject', 'RPEFreeLearner_egreedy',
           'RPEFreeLearner_esoftmax', 'RPEFreeLearner_softmax', 'RandomAgent',
           'RewardLearner', 'RewardLearner_acceptreject',
           'RewardLearner_egreedy', 'RewardLearner_esoftmax',
           'RewardLearner_softmax', 'SARSALearner', 'SARSALearnerHM',
           'SARSALearnerHM_acceptreject', 'SARSALearner_acceptreject',
           'SARSALearner_egreedy', 'SARSALearner_esoftmax',
           'SARSALearner_softmax', 'VanillaRNN', 'agents', 'base', 'classical',
           'de_i', 'de_lt', 'df_i', 'df_i_os', 'df_lt', 'df_lt_os',
           'draw_optimization_history', 'draw_schedule', 'environment', 'esa',
           'evaluation', 'f_i', 'f_i_hv', 'f_i_os', 'f_lt', 'f_lt_hv',
           'f_lt_os', 'f_rf', 'ffnn', 'generate_params_from_fits',
           'generate_random_child', 'generate_random_schedule',
           'generate_random_schedule_with_blocks', 'generators',
           'genetic_optimization', 'get_agent_bias', 'get_agent_failure',
           'get_agent_history', 'get_agent_performance',
           'get_agent_separation', 'get_agent_value_history',
           'get_continuous_cmap', 'get_schedule_fitness',
           'get_schedule_histories', 'get_schedule_values', 'gym',
           'hex_to_rgb', 'i', 'i_hv', 'i_os', 'lt', 'lt_hv', 'lt_os', 'nn',
           'optimize', 'phenomenological', 'phi', 'qlearning', 'rf',
           'rgb_to_dec', 'rnn', 'sa', 'static', 'thermal_annealing',
           'thermal_reshuffle', 'utils', 'visualization', 'ymaze_RNN',
           'ymaze_baiting', 'ymaze_dynamic', 'ymaze_fixedreward',
           'ymaze_gammatest', 'ymaze_static']
